### ISSUE TITLE
My terminal is alacritty, why does my color scheme not take effect

### ISSUE THREAD

**Issue by Ruixi-rebirth** [dracula/ranger#2]
![image](https://user-images.githubusercontent.com/75824585/140648069-7169f1cc-f5ed-4c8f-9392-2835fcfd7d6f.png)

**Comment by Ruixi-rebirth** [comment]
I checked the number in your anger color matching file corresponding to 256 colors, that is to say, the color matching in .Xresource does not work, but when I execute xrdb -query -all in my terminal, there is output .I don't understand

**Comment by Ruixi-rebirth** [comment]
I'm sure that Xresources has nothing to do with dracula.py

**Comment by thalesnunes** [comment]
You are totally correct! Xresources actually doesn't have anything to do with it, I actually ended up not considering terminals other than the ones that use Xresources to get colors (like xterm, urxvt, etc).

Can you tell me if you are using the Dracula theme for alacritty (https://draculatheme.com/alacritty)?
The dracula.py script should use your 16 colors, so I imagine that if you use alacritty's dracula theme, it should work!

I will try to implement a more "independent" solution soon, not relying on the terminal theme.

**Comment by Ruixi-rebirth** [comment]
Thank you, I studied all night. I like your ranger's color scheme very much, so what does your current plan look like? Please tell me, I really like it!

**Comment by thalesnunes** [comment]
Can you tell me if you are using the Dracula theme for alacritty (https://draculatheme.com/alacritty)?
The dracula.py script should use your 16 colors, so I imagine that if you use alacritty's dracula theme, it should work!

Besides that, I was looking for a way so that ranger colors don't depend on your terminal's, and from what I found, I think the 256 color pattern can be used! I'll look more into it, and keep you updated!

**Comment by thalesnunes** [comment]
Just to keep you updated, I tested alacritty with the dracula theme (https://draculatheme.com/alacritty), and the ranger theme seems to work the way it's supposed to!

I'll definetly look into implementing a more definite solution not depending on the terminal colorscheme, but for now, you can use the alacritty dracula theme and ranger will follow it.

If you have any more problems, please let me know!

**Comment by Ruixi-rebirth** [comment]
Thanks, I have adopted the scheme you said and it works perfectly
